_BASE_: "../Base-TripleBranchRCNN-FPN_new.yaml"
MODEL:
  RPN_ATTENTION: True
  MASK_ON: True
  RESNETS:
    DEPTH: 101
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8 
    DEFORM_ON_PER_STAGE: [False, False, True, TRue]
    DEFORM_MODULATED: True
    DEFORM_NUM_GROUPS: 1
  ROI_TRIPLE_BRANCH_WHOLE_MASK_HEAD: 
    BRANCH_GUIDANCE: True
    CONSIS_LOSS: True
    CONSIS_LOSS_MODE: "MX"
SOLVER:
  STEPS: (1000, 1300)
  MAX_ITER: 1500
